Initial set path implementation
Dhii/container-helper-base pull request #18
Opened 2018-04-04 15:11 UTC by romalytvynenko

Fixes #17

2018-04-05 08:30 UTC, XedinUnknown requested changes

2018-04-05 08:30 UTC, XedinUnknown commented on src/ContainerSetPathCapableTrait.php
> +            return;
Looks like an exception should be thrown here.

2018-04-05 08:30 UTC, XedinUnknown commented on src/ContainerSetPathCapableTrait.php
> +        if (count($path) === 1) {
Counting twice.

2018-04-05 08:30 UTC, XedinUnknown commented on src/ContainerSetPathCapableTrait.php
> +        $popped = array_shift($path);
A shifted piece is called `$popped`... I would say, something more semantic, like `$currentSegment`.

2018-04-05 14:45 UTC, XedinUnknown requested changes

2018-04-05 14:45 UTC, XedinUnknown commented on test/unit/ContainerSetPathCapableTraitTest.php
> +    public function createContainer($methods = [])
No docs

2018-04-05 14:45 UTC, XedinUnknown commented on src/ContainerSetPathCapableTrait.php
> +     * @throws InvalidArgumentException    If the container is invalid.
Here and in many other places - undefined (unimported) types.

2018-04-05 14:45 UTC, XedinUnknown commented on test/unit/ContainerSetPathCapableTraitTest.php
> +     * @return Exception The new exception.
Looks like undefined type.

2018-04-05 14:45 UTC, XedinUnknown commented on test/unit/ContainerSetPathCapableTraitTest.php
> +     * @return MockObject|RootException|InvalidArgumentException The new exception.
Looks like undefined type

2018-04-05 14:53 UTC, XedinUnknown requested changes

2018-04-05 14:53 UTC, XedinUnknown commented on src/ContainerSetPathCapableTrait.php
> +     * @throws OutOfRangeException
Missing description for when this exception type is thrown.

2018-04-05 14:53 UTC, XedinUnknown commented on src/ContainerSetPathCapableTrait.php
> +
Extra line for nothing

2018-04-05 14:53 UTC, XedinUnknown commented on test/unit/ContainerSetPathCapableTraitTest.php
> +            ->disableArgumentCloning()
Are you sure that this, and the proxying, are needed here?

2018-04-05 14:53 UTC, XedinUnknown commented on test/unit/ContainerSetPathCapableTraitTest.php
> +     * @return Exception The new exception.
Still undefined, @romalytvynenko.

2018-04-05 14:53 UTC, XedinUnknown commented on test/unit/ContainerSetPathCapableTraitTest.php
> +            ->will(
No problem if this goes on 1 line.

2018-04-05 14:53 UTC, XedinUnknown commented on test/unit/ContainerSetPathCapableTraitTest.php
> +        $reflection = new ReflectionMethod($subject, '_containerSetPath');
Here and in other test, use `Xpmock` reflection method.

2018-04-05 16:30 UTC, XedinUnknown commented on test/unit/ContainerSetPathCapableTraitTest.php
> +        $reflection = new ReflectionMethod($subject, '_containerSetPath');
Can't do that, because `Xpmock` will not allow passing arguments by reference, which is required by the SUT.

2018-04-06 07:52 UTC, XedinUnknown commented
Not strictly related to this PR, but to #15, [report.txt][] contains errors produced by Phan.

[report.txt]: https://github.com/Dhii/container-helper-base/files/1883140/report.txt

2018-04-06 10:16 UTC, XedinUnknown requested changes
Please update the changelog

2018-04-06 10:16 UTC, XedinUnknown commented on src/ContainerSetPathCapableTrait.php
> +     * @throws OutOfRangeException
@romalytvynenko, still missing.

2018-04-06 10:16 UTC, XedinUnknown commented on src/ContainerSetPathCapableTrait.php
> +
Still extra.

2018-04-06 10:18 UTC, XedinUnknown commented on src/ContainerSetPathCapableTrait.php
> +        if (is_array($container)) {
Looks like this scenario is not covered by a test.

2018-04-06 10:52 UTC, romalytvynenko commented
@XedinUnknown, covered all scenarios and add entry to changelog&readme

2018-04-10 14:32 UTC, XedinUnknown approved these changes

2018-04-10 14:32 UTC, merged